# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.FileField(upload_to='storage')),
                ('html_field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='filestorage',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.FormStorage'),
        ),
    ]
